### PR TITLE
Insert a full stop at the end of a sentence for some translations.

### PR DESCRIPTION
**Pull request by tinagerber**
Since several translations have already been adapted in this sprint, I have dispensed with a CHANGELOG entry.

Jira: https://4teamwork.atlassian.net/browse/NE-512

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

### CODE REVIEW

**Review by njohner — COMMENTED** [review]
I guess those affect the API. This means they are breaking changes...

**Comment by tinagerber** [comment]
So, do you think a change to an error message should be listed as a breaking change in the API changelog?

**Comment by lukasgraf** [comment]
@tinagerber yes, because are currently the only way a client could recognize why one of those workflow transitions has failed. That's why I marked them with `MARKER: used-in-api-response` in the `.po` files, and didn't touch them during my English translations.

In my opinion it simply wasn't worth the risk of breaking external applications. I would holf off on this issue for now, and double check with PO first whether we really want to take that risk for some typos. And if we do change it, it definitely needs a breaking API changelog entry, unfortunately.

**Comment by lukasgraf** [comment]
Or in other words: If we do change these API responses, we should change them _once_ in a way where we output a machine readable identifier that never changes (like `no_all_documents_checked_in`) in addition to human readable error messages, so that the translated messages become irrelevant.

**Comment by phgross** [comment]
I just talked to our two biggest "API clients" (RIS, UBit-Laufwerk), they're not using the transitions endpoint at all or at least they're not making a specific error handling. 

IMHO i don't think its a big risk to change the messages. A corresponding error handling would have been based on a translated error message and would have been implemented in a very "shaky" way. So my proposal would be, to add a API Changelog Entry to the actual changes. 

@lukasgraf @njohner what you think?

**Comment by njohner** [comment]
I'd agree that if we change the messages, we might as well go for something machine readable.

**Comment by lukasgraf** [comment]
Exactly, I agree with @njohner.
👍 for a breaking API change (thanks @phgross for checking with stakeholders), but I would use this chance to return, for the errors, both a machine readable identifier (e.g. `error_invalid_end_date`) as well as the (fixed) human readable message.

**Review by elioschmutz — APPROVED** [review]

**Comment by elioschmutz** [comment]
Sorry, ignore my approvement! Was not the right PR 🙈

**Pull request closed without merging**
