### PR TITLE
REST-API: Handle workspace invitations

### PR DESCRIPTION
**Pull request by elioschmutz**
Das GEVER-UI benötigt einen Endpoint zum Anzeigen von Teamraum-Einladungen sowie zum Annehmen und Ablehnen von Einladungen.

Dieser PR implementiert die entsprechenden Endpoints.

Issuer: https://github.com/4teamwork/gever-ui/issues/21
## Checkliste

_Zutreffendes soll angehakt stehengelassen werden._

- [x] Changelog-Eintrag vorhanden/nötig?
- [x] Aktualisierung Dokumentation vorhanden/nötig?

### CODE REVIEW

**Comment by lukasgraf** [comment]
Dafuq?
No review by GEVER-Team? No documentation for the API, even though `[x] Aktualisierung Dokumentation vorhanden/nötig?` is checked?

**Comment by elioschmutz** [comment]
@lukasgraf 🤔 something went wrong! there was a doc! I'll repush another PR.

It only affects the teamraum implementation in GEVER. Isn't @maethu a GEVER-Team Member since he is developing the GEVER-Teamraum as well?

**Comment by maethu** [comment]
I'm PO, not a Dev currently. @elioschmutz as before please add the GEVER-Team as Reviewer too. I don't know the QA/Review guidelines they have in particular.

**Comment by lukasgraf** [comment]
Please do.

No. He's barely involved in GEVER-Development. He's not taking part in our weeklies / daily standups or sprint planning, deploying GEVER-Releases to customers, etc.. He's got enough other work to deal with ;)

When doing PR's do `opengever.core` please pick the `4teamwork/gever` team as reviewers.

**Comment by elioschmutz** [comment]
👍 I'll do it

**Pull request merged**
