### PR TITLE
Remove KuB field `postOfficeBoxText` from fixtures

### PR DESCRIPTION
**Pull request by 2e12**
The fields `postOfficeBoxText` and `postOfficeBox` will be unifed into the the field `postOfficeBox` to simplify the KuB Schema.

You can find the KuB changes here -> https://github.com/4teamwork/kub/pull/179

Those changes will be interdouced with the upcoming KuB version 2022.14.0 
https://github.com/4teamwork/kub/releases/tag/2022.14.0

For [HG-2993]

[HG-2993]: https://4teamwork.atlassian.net/browse/HG-2993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by njohner** [comment]
Thanks for the PR. I've regenerated the responses from the current KuB version. It seems there have been some more changes since we last did that. I'll fix the tests if necessary.

**Comment by njohner** [comment]
I've updated the KuB fixture in KuB (https://github.com/4teamwork/kub/pull/185) and then used that to update the example responses in the kub testing.

**Review by tinagerber — APPROVED** [review]
LGTM. Just wondering if there is documentation somewhere on how to update the sample responses in kub testing.

**Comment by njohner** [comment]
I'll pretend there is in the testing file itself: https://github.com/4teamwork/opengever.core/pull/7620/files#diff-059fa2261a7751d27ab92735c3780600382067534a5e0bf547382b1eb3b59e0fL38-L39
Setting up KuB for local development and loading the testing fixture is documented in the KuB project.

**Pull request merged**
