### PR TITLE
Register OGDS group and user endpoints on the plone siteroot instead on a contactfolder

### PR DESCRIPTION
**Pull request by elioschmutz**
The endpionts `@ogds-users`, `@ogds-groups`, `@ogds-user-listing` and `@ogds-group-listing` are currently registered on a contactfolder. This means, we can only list groups and users or fetch additional information if we also have a contactfolder on the plonesite. Registering it only on a contact-folder seems to be wrong because ogds-users and ogds-groups have nothing to do with the contactfolder. It should be possible to fetch users and groups even if there is no contactfolder.

This PR registers the endpoint `@ogds-users`, `@ogds-groups`, `@ogds-user-listing` and `@ogds-group-listing` on the plone site root. The endpoints are no longer available on the contactfolder.

Jira: https://4teamwork.atlassian.net/browse/NE-83

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

## Checklist (if applicable)

_Only applicable should be left and checked._

- API change:
  - [x] Documentation is updated
  - If breaking:
    - [x] api-change label added
    - [x] #delivery channel notified about breaking change
    - [x] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

### CODE REVIEW

**Review by deiferni — COMMENTED** [review]
just for the record, we've registered it on the contact folder to able to restrict access via contact folder permissions, namely to `Reader` on the contact folder. I think we can loosen that restriction as IIRC we don't actually restrict contact folder `View` in any case.

With this change we bind permission to what is set on the plone site, which is probably fine. Please double-check the permissions and make sure that we don't expose the endpoint to `Anonymous` which would be bad.

**Review by deiferni — COMMENTED** [review]
LGTM apart from thoughts in previous comment.

**Comment by elioschmutz** [comment]
> just for the record, we've registered it on the contact folder to able to restrict access via contact folder permissions, namely to `Reader` on the contact folder. I think we can loosen that restriction as IIRC we don't actually restrict contact folder `View` in any case.
> 
> With this change we bind permission to what is set on the plone site, which is probably fine. Please double-check the permissions and make sure that we don't expose the endpoint to `Anonymous` which would be bad.

Every endpoint has the `zope2.View` permission. And gever or teamraum is never accessible by anonymous users. The `@users` endpoint was already accessible with the same premission on the plone root: https://github.com/4teamwork/opengever.core/pull/5779

So it should be fine 👍

**Comment by elioschmutz** [comment]
> LGTM apart from thoughts in previous comment.

could you approve?

**Review by deiferni — APPROVED** [review]

**Pull request merged**
