### PR TITLE
Add second language to the testservers by default.

### PR DESCRIPTION
**Pull request by deiferni**
For testing language switcher in UI @all4manu would like to have a second language which is always enabled. This seems to work with all existing tests in the backend.

Jira: https://4teamwork.atlassian.net/browse/HG-995

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] ~~Changelog entry~~
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

### CODE REVIEW

**Review by njohner — APPROVED** [review]
LGTM

**Comment by deiferni** [comment]
@all4manu please let me know when you are ready for these changes in the UI.

**Comment by all4manu** [comment]
@deiferni go ahead and 🚢

**Comment by elioschmutz** [comment]
@deiferni this PR broke the E2E tests. Is it possible to revert it until the tests are fixed in https://github.com/4teamwork/gever-ui/pull/1632? Otherwise, it will block other frontend PRs...

**Comment by deiferni** [comment]
@elioschmutz i just had a look at this with @all4manu and he is on it with https://github.com/4teamwork/gever-ui/pull/1632. It may be fixed now, otherwise we can take further action!

**Pull request merged**
