### PR TITLE
Bump `plone.restapi` to 6.14.0 get fix for bytestring ordering and catch up with changes.

### PR DESCRIPTION
**Pull request by deiferni**
To prepare a potential upstream of https://github.com/4teamwork/opengever.core/pull/6568 we should also catch up with recent changes to `plone.restapi`. I quickly tried it out and according to our tests the changes are manageable.

I've gone through the changelog and have not found anything with obviously critical impact. I'd be glad for a 2nd opinion though, especially regarding:
- https://github.com/plone/plone.restapi/pull/951/
- https://github.com/plone/plone.restapi/pull/909/

To catch up wich changes i had to adapt the following:
 - add next/prev to tests as of https://github.com/plone/plone.restapi/pull/901
- validation error serialization has changed a bit. IMO for the worse, but it it should still be ok the way it is now.
- drop monkey patch which is now upstream

This is currently a draft. I would only merge after our next release and after we ensure:
- [x] UI-tests against this branch still work correctly
- [x] 2nd opinion of no critical features added/changed

Jira: https://4teamwork.atlassian.net/browse/CA-809

_We have added the `api-change` label due to the version bump of `plone.restapi`. We don't expect things to actually break._

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

## Checklist (if applicable)

_Only applicable should be left and checked._

- API change:
  - If breaking:
    - [x] api-change label added
    - [x] #delivery channel notified about breaking change
    - [x] Scrum master is informed

### CODE REVIEW

**Review by lukasgraf — COMMENTED** [review]
Your side of the changes LGTM 👍 
I had a cursory look at the two restapi changes specifically mentioned, and I didn't see any obvious issues for us. Will have a closer look again though.

**Review by lukasgraf — APPROVED** [review]
LGTM 👍 - I had a closer look at the two PRs mentioned, and I don't see any issues for us.

**Comment by deiferni** [comment]
ui ok according to https://4teamwork.slack.com/archives/C019ENVUY0J/p1601450760007800?thread_ts=1601392476.007300&cid=C019ENVUY0J

**Comment by deiferni** [comment]
✅ &nbsp; apps probably ok 😉  as of https://4teamwork.slack.com/archives/C011C318H7H/p1601544130009200?thread_ts=1601469361.007700&cid=C011C318H7H

**Pull request merged**
