### PR TITLE
Add checkbox to ToDos to show if they are completed

### PR DESCRIPTION
**Pull request by pareiss**
All ToDos now have a checkbox that shows if they are completed or not.

image

For [TI-917]

## Checklist
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

[TI-917]: https://4teamwork.atlassian.net/browse/TI-917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by elioschmutz** [comment]
@pareiss could you upload a printscreen of the pdf to the pr description? thanks!

**Comment by pareiss** [comment]
@elioschmutz Done

**Comment by elioschmutz** [comment]
As already discussed, using the character: &#9745; (☑) seems not to be possible to use. I think because of a font issue.

But we could build such a checkbox with plain html and css:

```
.checkbox-container {
    display: flex;
    align-items: center;
}

.custom-checkbox {
    width: 20px;
    height: 20px;
    border: 2px solid #888;
    border-radius: 4px;
    position: relative;
}

.checkbox-container .custom-checkbox.checked::after {
    content: '';
    position: absolute;
    left: 6px;
    top: 2px;
    width: 5px;
    height: 10px;
    border: solid #888;
    border-width: 0 2px 2px 0;
    transform: rotate(45deg);
}
```

and then use it with: 

```
    <div class="checkbox-container">
        <div class="custom-checkbox" style="margin-right: 1em"></div>
    </div>
    <div class="checkbox-container">
        <div class="custom-checkbox checked"></div>
    </div>
```

this will produce the following checkboxes:

Bildschirmfoto 2024-09-11 um 11 20 38

You could use this instead.

**Comment by pareiss** [comment]
@elioschmutz Thank you for the recommendation. I implemented it, see the new scrrenshot.

**Comment by elioschmutz** [comment]
could you cleanup your commits? the first commit is no longer required. so you can remove it.

**Comment by pareiss** [comment]
Done, only one commit.

**Review by elioschmutz — COMMENTED** [review]
Your PR-title and description is now outdated. please update it according to your newest changes.

And please use a more specific commit message. I.e. `Show toto completed state in meeting pdf`

**Comment by pareiss** [comment]
Thanks for your patience ill have to put more effort into checking things continiously in the future to make it so PRs are accepted faster.

**Review by elioschmutz — APPROVED** [review]

**Pull request merged**
