### PR TITLE
Add support for filters in listing endpoint

### PR DESCRIPTION
**Pull request by buchi**
Filters can be passed with the `filters` record query parameter.

Example:
`/@listing?name=dossiers&filters.review_state:record:list=dossier-state-active&filters.review_state:record:list=dossier-state-archived&filters.responsible:record=hugo.boss`

### CODE REVIEW

**Comment by buchi** [comment]
The listing endpoint is intentionally not documented yet as it's not public.
We are developing it for the new gever-ui and want to be able to break compatibility if required.

**Comment by deiferni** [comment]
the listing endpoint is also used in other internal projects such as ris. i'd rather mention in the docs that it is not considered stable yet.

**Comment by buchi** [comment]
This PR ist not about adding the listing endpoint and thus also not about adding documentation for it.
It just adds an additional option.

I'll add the documentation in a separate PR.

**Comment by buchi** [comment]
documentation is in #5494

**Pull request merged**
