### PR TITLE
Readd Office template, macro, stencil files into Office Connector editable MIME types

### PR DESCRIPTION
**Pull request by Rotonen**
We're readding Office Connector editability for Office template formats, as they work on Windows.

Closes https://github.com/4teamwork/opengever.core/issues/5453

### CODE REVIEW

**Comment by Rotonen** [comment]
We cannot guarantee any macro type to work on any platform.
We cannot guarantee any addin type to work on any platform.

The empty skeleton files of all the variants work on Windows.

We can blacklist template MIME types in macOS client policies for now, if desired.

Added Excel addin dependent and binary macro enabled formats.
Added Powerpoint addin dependent, slideshow and template macro enabled formats.
Added all Visio drawing, stencil and template macroenabled formats.

**Comment by deiferni** [comment]
(as discussed, double-check mimetypes registry)

**Comment by Rotonen** [comment]
@deiferni we indeed had some stuff not present in the document MIME type registry - added a test to ensure everything on the default editables list is present in that registry.

Ready for rereview.

**Comment by Rotonen** [comment]
As per discussion I'm dropping the added test and most of the changes to our extra types.

https://github.com/python/cpython/blob/2.7/Lib/mimetypes.py#L40-L50

https://github.com/python/cpython/blob/2.7/Lib/mimetypes.py#L405-L536

We want to minimise mucking around with the Python mimetype registry as per how it works under the hood.

I'm leaving in the a change to fix the entry for the powerpoint macro enabled template in the extra registry entries we provide.

**Pull request merged**
