### PR TITLE
Update businesscasedossier schema in dev documentation.

### PR DESCRIPTION
**Pull request by tinagerber**
The schema seems to be out of date.

Definition of Done: https://4teamwork.atlassian.net/wiki/spaces/CHX4TW/pages/917562/

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] Changelog entry
- [ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)

### CODE REVIEW

**Comment by tinagerber** [comment]
Since the tests on the master are green, we probably do not have such a test.

**Comment by mbaechtold** [comment]
Danke, das ist mir auch aufgefallen: https://github.com/4teamwork/opengever.core/pull/6546/commits/45125b9e3a24a0a3322b0d026cded4ec0cb48a4b

**Comment by deiferni** [comment]
@tinagerber my thinking was more along the lines of it may be there but not work any more. have you checked?

**Comment by tinagerber** [comment]
I haven't found such a test, but I wouldn't know exactly where to look for it either.

**Pull request merged**
