### PR TITLE
Reindex SearchableText (dossier) after changing the comment thru the overlay

### LINKED ISSUE #2574: Aktennotiz: SearchableText wird bei Aktualisierung Kommentarfeld nicht aktualisiert
Bearbeite ich das Kommentarfeld über das Symbol in der Byline, wird nach dem Speichern offenbar der SearchableText nicht aktualisiert. 

Bearbeite ich jedoch danach das Dossier (über "Bearbeiten") und speichere es wieder, findet dann die Volltextsuche den eingegebenen Kommentar.

### PR DESCRIPTION
**Pull request by maethu**
Closes #2574

### CODE REVIEW

**Comment by maethu** [comment]
main-thumb-t-1502130-200-mkjvumlwzgnsdjllrnqdubwlpbejgtlu

**Comment by lukasgraf** [comment]
@maethu the tree is because the file is called `save_comments_entpoint.py` I assume 😉 ?

**Comment by maethu** [comment]
@lukasgraf no, it's a "low hanging fruit" (the PR)

**Comment by lukasgraf** [comment]
@maethu `IDisableCSRFProtection` is a measure of last resort - see http://devblog.4teamwork.ch/blog/2015/10/12/debugging-csrf-protection-false-positives-in-plone/

I'd prefer if we could actually pass the CSRF token, or at the very least, use `unprotectedWrite()` instead of disabling CSRF protection entirely.

**Comment by deiferni** [comment]
(sorry i missed that one, i agree!)

**Pull request merged**
