### PR TITLE
Unify CI scripts, start with pycodestyle

### PR DESCRIPTION
**Pull request by Rotonen**
* Kill the separate jobs per QA tool
* Have just one which also respects the excludes from the individual tool configs
* Only enable `pycodestyle` for now

### CODE REVIEW

**Comment by Rotonen** [comment]
I've now amended `bin/qa` to also respect per tool exlusions from per tool config files.

**Comment by Rotonen** [comment]
I've also added a `bin/shellcheck` soft fail wrapper for notifying the user / CI shellcheck is not installed.

**Comment by Rotonen** [comment]
A local test run:

```
bin/qa

Detected changes in this branch in the following Python files:
bootstrap.py
opengever/advancedsearch/skins/advancedsearch_resources/livesearch_reply.py
opengever/trash/tests/__init__.py
opengever/trash/trash.py

Running pycodestyle.
opengever/trash/trash.py:15:1: E303 too many blank lines (3)
opengever/trash/trash.py:31:1: E265 block comment should start with '# '
opengever/trash/trash.py:67:9: E265 block comment should start with '# '
opengever/trash/trash.py:82:1: E305 expected 2 blank lines after class or function definition, found 0
opengever/trash/trash.py:164:17: E303 too many blank lines (2)

```

* Changes in a skins directory
* Changes in a tests directory
* Changes in bootstrap.py
* Changes in a legit file as well

**Comment by Rotonen** [comment]
@deiferni also a test run on top of your previously cranky branch:

```
(2.7.13/envs/opengever.core) joni@rotobock:~/koodaus/git/opengever.core$ git rebase origin/deif-committee-lawigver
First, rewinding head to replay your work on top of it...
Applying: Sort bin/.gitignore excludes.
Applying: Add a script to list changes in our current branch/fork.
Applying: Add a script to list changed files in our current branch/fork.
Applying: Add a script to list changed .py in our current branch/fork.
Applying: Add a script to list changed .sh in current branch/fork.
Applying: Add a script for listing changed xml files in branch/fork.
Applying: Add a conditional shellcheck wrapper.
Applying: Kill the separate test qa runner jobs and make a unified one.
```

```
(2.7.13/envs/opengever.core) joni@rotobock:~/koodaus/git/opengever.core$ bin/qa

Detected changes in this branch in the following Python files:
opengever/base/tests/test_pathbar.py
opengever/core/cached_testing.py
opengever/core/tests/base.py
opengever/core/tests/test_lawgiver_workflows.py
opengever/core/upgrades/20170810102405_install_ftw_lawgiver/__init__.py
opengever/core/upgrades/20170810102405_install_ftw_lawgiver/upgrade.py
opengever/core/upgrades/20170810102518_add_new_committee_roles/__init__.py
opengever/core/upgrades/20170810102518_add_new_committee_roles/upgrade.py
opengever/core/upgrades/20170810102557_configure_administrator_and_publisher_roles/__init__.py
opengever/core/upgrades/20170810102557_configure_administrator_and_publisher_roles/upgrade.py
opengever/core/upgrades/20170810142533_remove_custom_committee_workflow_actions/__init__.py
opengever/core/upgrades/20170810142533_remove_custom_committee_workflow_actions/upgrade.py
opengever/core/upgrades/20170822122453_replace_committee_group_member_role/__init__.py
opengever/core/upgrades/20170822122453_replace_committee_group_member_role/upgrade.py
opengever/core/upgrades/20170822144010_enable_committee_lawgiver_workflows/__init__.py
opengever/core/upgrades/20170822144010_enable_committee_lawgiver_workflows/upgrade.py
opengever/document/tests/test_document.py
opengever/document/tests/test_overview.py
opengever/meeting/browser/committee.py
opengever/meeting/browser/committeeforms.py
opengever/meeting/browser/committeetransitioncontroller.py
opengever/meeting/committee.py
opengever/meeting/committeeroles.py
opengever/meeting/model/committee.py
opengever/meeting/model/proposal.py
opengever/meeting/tests/test_agendaitem.py
opengever/meeting/tests/test_agendaitem_list.py
opengever/meeting/tests/test_agendaitem_word.py
opengever/meeting/tests/test_close.py
opengever/meeting/tests/test_committee.py
opengever/meeting/tests/test_committee_container.py
opengever/meeting/tests/test_committee_roles.py
opengever/meeting/tests/test_excerpt.py
opengever/meeting/tests/test_locking.py
opengever/meeting/tests/test_meeting.py
opengever/meeting/tests/test_meeting_zipexport.py
opengever/meeting/tests/test_members.py
opengever/meeting/tests/test_memberships.py
opengever/meeting/tests/test_pathbar.py
opengever/meeting/tests/test_periods.py
opengever/meeting/tests/test_proposal_listings.py
opengever/meeting/tests/test_proposalhistory.py
opengever/meeting/tests/test_protocol.py
opengever/meeting/tests/test_unit_agenda_item.py
opengever/sharing/browser/sharing.py
opengever/sharing/tests/test_sharing_integration.py
opengever/testing/fixtures.py
opengever/testing/integration_test_case.py
opengever/testing/pages/breadcrumbs.py
opengever/testing/test_case.py
setup.py

Running pycodestyle.

Found nothing to complain about. Well done!

```

**Comment by deiferni** [comment]
okey then!

**Pull request merged**
