### PR TITLE
No longer hide Download PDF link in the bumblebee overlay for mails.

### LINKED ISSUE #1946: Mail-Vorschau: PDF kann nicht heruntergeladen werden
Wird im Menübalken rechts nicht angeboten...
bildschirmfoto 2016-06-17 um 16 22 05

### PR DESCRIPTION
**Pull request by phgross**
Bumblebee supports now mail conversion. Fixes #1946.

@elioschmutz or @deiferni please have a 👀

### CODE REVIEW

**Comment by elioschmutz** [comment]
Von mir ein 👍

**Comment by deiferni** [comment]
👍  plz rebase

**Comment by phgross** [comment]
@deiferni updated ...

**Comment by phgross** [comment]
@deiferni updated ...

**Comment by deiferni** [comment]
👍

**Pull request merged**
