### PR TITLE
Enable ftw.chameleon

### LINKED ISSUE #2287: Chameleon support
Port the views and tests to support Chameleon as the templating engine.

At this point it seems like there are only very minor changes in locale dependent date rendering and some minor templating differences.

### PR DESCRIPTION
**Pull request by Rotonen**
* Formatting fixes
* Depend on `ftw.chameleon`
  * Do we want to pin this somewhere?
  * This has potential implications for deployments:
    * https://github.com/4teamwork/ftw.chameleon#installation
* Fix a test which relied on attribute order
* Fix a missing `</div>` in the content disposition overlay template

Closes #2287

### CODE REVIEW

**Comment by Rotonen** [comment]
@deiferni https://github.com/4teamwork/ftw-buildouts/blob/master/plone-development.cfg#L35

Chameleon is already in our development buildouts, though?

**Comment by Rotonen** [comment]
@deiferni https://github.com/4teamwork/ftw-buildouts/blob/master/production.cfg#L53

Also for production.

Chameleon creates a cache dir if one does not exist:
https://github.com/malthe/chameleon/blob/a6df9f3451719d4d8e2e43dc13ed8d7689493182/src/chameleon/template.py#L48

Except when we define one:
https://github.com/malthe/chameleon/blob/f768ded5fc7e5f6eb1e5a1adce31db72a3049aa6/src/chameleon/config.py#L36

Relevant pull request: 4teamwork/gever-buildouts/pull/10

**Comment by deiferni** [comment]
Buildout-PR is merged. There is a part i can't find though, i think we should also define `instance0` env-vars for production as specified in https://github.com/4teamwork/ftw.chameleon#installation. I can only find where these variabls are defined in the `buildout` part, but i can't see if we already define the environment vars somewhere. If we don't do that yet could you also do that in another PR? Or point me to the location where that stuff actually happens if i missed it 😉 .

```
[instance0]
environment-vars +=
    CHAMELEON_EAGER …
    CHAMELEON_RELOAD …
    FTW_CHAMELEON_RECOOK_WARNING …
```

**Comment by Rotonen** [comment]
@deiferni nope, we both missed that.

https://github.com/4teamwork/gever-buildouts/blob/bdc76aa58f7d457aa41f35cb3507069ec8c62a0e/standard-deployment.cfg#L46

**Comment by deiferni** [comment]
that's just the cache though 🤔 ?

**Comment by Rotonen** [comment]
@deiferni yes, we missed adding it before merging in the pull request on gever-buildouts.

**Comment by deiferni** [comment]
no problemo, can be done separately as already mentioned in https://github.com/4teamwork/gever-buildouts/pull/10 😉

**Comment by Rotonen** [comment]
Will land with 4teamwork/gever-buildouts/pull/11 .

Go time?

**Comment by deiferni** [comment]
rebase time 😉

**Comment by Rotonen** [comment]
@deiferni do try the online mergetool as the changelog is the only thing conflicting?

**Comment by deiferni** [comment]
unfortunately that creates undesired commits and would require a rebase anyway after using it

**Comment by Rotonen** [comment]
@deiferni was not aware of it being not able to rebase - rebased.

**Comment by deiferni** [comment]
@Rotonen could you also verify that everything is pinned (`ftw.chameleon`, `chameleon`, …?)

**Comment by Rotonen** [comment]
@deiferni go time?

**Pull request merged**
