### PR TITLE
Forbid transitions linked to dossier offer process through RESTAPI.

### LINKED ISSUE #5432: REST API Endpoint für Dossier Status Wechsel
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

Zurzeit ist der Dossier Abschluss via `@workflow` endpoint zwar möglich, führt aber keine Inhaltsprüfungen und auch anschliessende Anpassungen (automatischer Abschluss von Subdossiers, Enddatum etc.) wird nicht korrekt gemacht.

Deshalb müssen für die Dossier Statuswechsel `abschliessen`, `stornieren`,  `wieder eröffnen (2x)` entsprechende `TransitionExtenders` registriert werden (siehe hierfür https://github.com/4teamwork/opengever.core/pull/5316).

**Abschluss** (separates Ticket: #5526)
 - [x] prüfen des Inhalts, sog. Abschlussregel
 - [x] Abschluss (`opengever.core.dossier.resolve.Resolver`) muss als TransitionExtender implementiert werden. Beinhaltet rekursiver Abschluss, setzen des Enddatums ...)
 - [x] ResolveLock muss beachtet werden. Hier ist noch nicht ganz klar wie dieses auf das neue Konzept überführt werden soll, aber es sollte nach Möglichkeit immer noch ein Locking während des Abschliessens stattfinden. _(Evtl. `@workflow` endpoint überschreiben und trotzdem noch eine View (für das UI) behalten)._
 
**Stornierung**
 - [x] Conditions prüfen
 - [x] Stornierung (gemäss `opengever.core.dossier.deactivate.DossierDeactivateView`) muss als TransitionExtender implementiert werden. Beinhaltet rekursiver Stornierung, setzen des Enddatums)

**Wieder eröffnen**
 - [x] Reaktivierung (gemäss `opengever.core.dossier.resolve.DossierReactivateView`) muss als TransitionExtender implementiert werden. Beinhaltet rekursive Reaktivierung, Entfernen des Enddatums)

**Anbieten, Archivieren, Aus Angebot entfernen (`offered-to-resolved`, `offered-to-inactive`)**
 - [ ] Transition via API muss verhindert werden, da nur via Angebotserstellung bzw. Veränderung  eine solche Transition möglich sein soll.

Migration von inkorrekten Daten: 
 - Ich würde hierfür wohl eine Management Ansicht erstellen, welche solche Dossier auflistet und darauf hinweist, da eine automatische Korrektur nicht in allen Fällen möglich ist. Zurzeit ist ein OGIP für solche Admin-Ansichten in Arbeit/geplant ich würde dies deshalb nicht als Teil dieses Issues umsetzen

### PR DESCRIPTION
**Pull request by njohner**
Certain dossiers transitions should not be allowed through the RESTAPI, as they are handled by a specific process in GEVER. This is the case of all the transitions linked to the offer/archive process.

We now reply to such requests with a 400 `BadRequest`.

This is part of and closes #5432

### CODE REVIEW

**Comment by njohner** [comment]
We have at least a few other transitions that do not define an action:
```
task-transition-open-planned
document-transition-initialize
proposal-transition-submit
proposal-transition-reject
```
With the changes I've made, these would also be forbidden through the RESTAPI. Not sure what we want here?
Also it will now reply with a `400 Bad Request` when the transition is not available for the `context` in its current review_state. So we basically map the `@workflow/transition_id` endpoint to the available workflow actions on the `context`.

**Comment by njohner** [comment]
@lukasgraf can you have another look at this one?

**Comment by lukasgraf** [comment]
@njohner was discussed: I believe this is what we want. The four transitions you listed should indeed be forbidden, because they are internal to some degree. And responding with `400 Bad Request` for a transition that isn't allowed is ok as well 👍

**Comment by njohner** [comment]
Ok I just rebased, so this is ready for review

**Comment by lukasgraf** [comment]
@njohner now tests seem to fail 🤕

**Pull request merged**
